name: build-apk-bggrgjqaubcoe-piliplus

on:
  workflow_dispatch:
  workflow_call:
  
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Clean runner environment
        run: |
          # 清理可能存在的全局缓存文件
          rm -rf ~/.gradle/caches/transforms-*
          rm -rf ~/.android/build-cache/

      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          repository: bggRGjQaUbCoE/PiliPlus
          ref: main
          fetch-depth: 0

      - name: Checkout ci source repo (self)
        uses: actions/checkout@main
        with:
          path: ci-source

      - name: Initialization values
        run: |
          echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV

      - name: Set up jdk 21
        uses: actions/setup-java@main
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties
            
      - name: Set up flutter
        uses: subosito/flutter-action@main
        id: flutter-action
        with:
          channel: stable # 更新周期3月
          # channel: beta # 更新周期1-2月
          # channel: dev # 更新周期1周
          # channel: master # 更新周期每天
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Apply bottom sheet patch
        working-directory: ${{ env.FLUTTER_ROOT }}
        run: git apply $GITHUB_WORKSPACE/lib/scripts/bottom_sheet_patch.diff
        continue-on-error: true
        
      - name: Decode and write keys
        # if: github.event_name == 'workflow_dispatch'
        run: |
          if [ ! -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.p12
            echo storeFile='key.p12' >> android/key.properties
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> android/key.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> android/key.properties
            echo keyPassword='${{ secrets.KEY_ALIAS_PASSWORD }}' >> android/key.properties
          fi
          
      - name: Set and extract version
        shell: pwsh
        run: lib/scripts/build.ps1 android
        
      - name: Flutter build release apk
        # run: flutter build apk --release --split-per-abi --dart-define-from-file=pili_release.json --pub
        # 改为仅编译arm64-v8a架构版本
        run: flutter build apk --release --target-platform=android-arm64 --split-per-abi --dart-define-from-file=pili_release.json --pub
        
      - name: Rename apk files
        run: |
          for file in build/app/outputs/flutter-apk/app-*-release.apk; do
            abi=$(echo "$file" | sed -E 's|.*app-(.*)-release\.apk|\1|')
            # mv "$file" "PiliPlus_android_${{ env.version }}_${abi}.apk"
            mv "$file" "piliplus-${{ env.BUILD_DATE }}.apk" 
          done
          # 配合仅编译arm64-v8a架构版本导致的文件名变化进行的修改
          # mv "build/app/outputs/flutter-apk/app-release.apk" "PiliPlus_android_${{ env.version }}_${abi}.apk"
        shell: bash
        
      - name: Erase keystore, encrypt package and create release
        uses: ./ci-source/.github/actions/erase-aes256pac-release/
        with:
          # 私密文件路径（基于github.workspace的绝对路径）
          P12_KEYSTORE_PATH: "/android/app/key.p12 /android/key.properties"
          ZIP_AES256_PWD: ${{ secrets.ZIP_AES256_PWD }}
          BUILD_ARTIFACT_PATH: "/piliplus-${{ env.BUILD_DATE }}.apk"
          RELEASE_TAG_NAME: "${{ env.BUILD_DATE }}-piliplus"