name: build-bggrgjqaubcoe-piliplus

on:
  workflow_dispatch:
  workflow_call:
  
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
jobs:
  build:
    name: Release Android
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    
      - name: Checkout MAIN source repo (fantasy-bv)
        uses: actions/checkout@main
        with:
          repository: bggRGjQaUbCoE/PiliPlus
          ref: main
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties
            
      - name: Set up Flutter
        uses: subosito/flutter-action@main
        id: flutter-action
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      
      - name: Apply bottom sheet patch
        working-directory: ${{ env.FLUTTER_ROOT }}
        run: git apply $GITHUB_WORKSPACE/lib/scripts/bottom_sheet_patch.diff
        continue-on-error: true
        
      - name: Write key
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ ! -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.p12
            echo storeFile='key.p12' >> android/key.properties
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> android/key.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> android/key.properties
            echo keyPassword='${{ secrets.KEY_ALIAS_PASSWORD }}' >> android/key.properties
          fi
          
      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1 android
        
      - name: Flutter build apk
        run: flutter build apk --release --split-per-abi --dart-define-from-file=pili_release.json --pub
        
      - name: Rename
        run: |
          for file in build/app/outputs/flutter-apk/app-*-release.apk; do
            abi=$(echo "$file" | sed -E 's|.*app-(.*)-release\.apk|\1|')
            mv "$file" "PiliPlus_android_${{ env.version }}_${abi}.apk"
          done
        shell: bash
        
      - name: Create GitHub Release & Upload APK
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{env.BUILD_DATE}}-piliplus
          files: |
              PiliPlus_android_*.apk
          draft: false
          prerelease: false