name: build-apk-xed-editor

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clean runner environment
        run: |
          # 清理可能存在的全局缓存文件
          rm -rf ~/.gradle/caches/transforms-*
          rm -rf ~/.android/build-cache/

      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          repository: Xed-Editor/Xed-Editor
          ref: main
          path: xed_editor_source
          fetch-depth: 0

      - name: Checkout ci source repo (self)
        uses: actions/checkout@main
        with:
          path: ci_source

      - name: Initialization values
        run: |
          echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV

      - name: Set up jdk 21
        uses: actions/setup-java@main
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      # app/build.gradle.kts中，硬编码了xed.keystore和signing.properties的路径
      # "/tmp/signing.properties"和"/tmp/xed.keystore"
      - name: Decode and create secrets
        run: |
          mkdir -p ./tmp
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ./tmp/xed.keystore
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" > ./tmp/signing.properties
          echo "keyPassword=${{ secrets.KEY_ALIAS_PASSWORD }}" >> ./tmp/signing.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> ./tmp/signing.properties

      - name: Clone submodules
        working-directory: ./xed_editor_source
        run: git submodule update --init --recursive

      - name: Build release apk files
        working-directory: ./xed_editor_source
        env:
          KEYSTORE_FILE: "${{ github.workspace }}/tmp/xed.keystore"
          SIGNING_PROPERTIES_FILE: "${{ github.workspace }}/tmp/signing.properties"
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon -Pandroid.ndk.abiFilters=arm64-v8a
          mkdir -p ./release-apks
          mv ./app/build/outputs/apk/release/*.apk ./release-apks/xed-editor-${{env.BUILD_DATE}}.apk

      - name: Erase keystore, encrypt package and create release
        uses: ./ci_source/.github/actions/erase_aes256pac_release/
        with:
          # 文件路径为基于github.workspace的绝对路径
          P12_KEYSTORE_PATH: "./tmp/xed.keystore ./tmp/signing.properties"
          ZIP_AES256_PWD: ${{ secrets.ZIP_AES256_PWD }}
          BUILD_ARTIFACT_PATH: "./xed_editor_source/release-apks/xed-editor-${{env.BUILD_DATE}}.apk"
          RELEASE_TAG_NAME: "${{ env.BUILD_DATE }}-xed-editor"